### PR TITLE
Add a datestamp postfix to scan dir name.

### PR DESCRIPTION
**Pull request by yusufm**

### CODE REVIEW

**Comment by JohnDMcMaster** [comment]
Hmm have to give this one some thought. I'm generally onboard with it though

**Comment by yusufm** [comment]
> 

I really just want to not have to type in a new name (or version postfix) for every related/retry scan. However that can be accomplished is fine.

**Comment by JohnDMcMaster** [comment]
IIRC this is inconsistent with how we do snapshots, but I think its better than what we have now. Long term we should have some options how to format output names...there is already some precedent for this (ex: the custom sipr0n naming widget)

**Comment by yusufm** [comment]
I did think of matching the scan date prefix, but was thinking it would be little easier to sort the dirs if the date was a postfix and have the same ones grouped together when looking through the dir list.

**Pull request merged**
