### PR TITLE
Removing UI elements when shared space set in config.

### PR DESCRIPTION
**Pull request by yusufm**

### CODE REVIEW

**Comment by JohnDMcMaster** [comment]
What is the goal of this addition? You already can't see the critical keys in the GUI (they are *'d out). I'd see more value in hiding the stitching tab entirely to simplify the UI, although maybe it would be better to just do that by default

**Comment by yusufm** [comment]
> What is the goal of this addition? You already can't see the critical keys in the GUI (they are *'d out). I'd see more value in hiding the stitching tab entirely to simplify the UI, although maybe it would be better to just do that by default

This seems to be the simplest change, keeping to the minimal work philosophy. It doesn't change much the current behavior, and hides the confusing entries. Only the email field is still displayed. We could hide the whole tab, but that removes the ability to kick of manual runs. 

Ideally the cloudstitch flow would get a redesign, but thats for a future date.

**Comment by JohnDMcMaster** [comment]
Ok so if I understand correctly then your goals are:
- Be able to manually kick off runs
- Remove confusing elements from the GUI

If that is the case, why don't we hide those fields unless you are in dev mode or remove them entirely? General users are going to specify them by config file anyway

**Comment by JohnDMcMaster** [comment]
Per discussion, I've instead merged a change that always hides these widgets unless in dev mode

**Pull request closed without merging**
